# Generated by Django 2.1.3 on 2018-11-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rgttestevent',
            options={'managed': False, 'ordering': ['test', 'event']},
        ),
        migrations.AlterModelOptions(
            name='testrgttestevent',
            options={'managed': False, 'ordering': ['test', 'event']},
        ),
    ]
