# Generated by Django 2.1.3 on 2018-11-08 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgt', '0002_auto_20181108_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rgttestevent',
            options={'managed': False, 'ordering': ['test_id', 'event_id']},
        ),
        migrations.AlterModelOptions(
            name='testrgttestevent',
            options={'managed': False, 'ordering': ['test_id', 'event_id']},
        ),
    ]
