# Generated by Django 2.1.3 on 2018-11-20 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rgt', '0003_auto_20181108_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='RgtFailure',
            fields=[
                ('failure_id', models.AutoField(primary_key=True, serialize=False)),
                ('failure_label', models.CharField(max_length=256)),
                ('failure_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rgt_failure',
                'ordering': ['failure_id'],
            },
        ),
        migrations.CreateModel(
            name='RgtTestFailure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('failure_details', models.TextField(blank=True, null=True)),
                ('failure_id', models.ForeignKey(db_column='failure_id', on_delete=django.db.models.deletion.DO_NOTHING, to='rgt.RgtFailure')),
                ('test_id', models.ForeignKey(db_column='test_id', on_delete=django.db.models.deletion.DO_NOTHING, to='rgt.RgtTest', unique=True)),
            ],
            options={
                'db_table': 'rgt_test_failure',
                'ordering': ['test_id', 'failure_id'],
            },
        ),
    ]
