# Generated by Django 2.1.3 on 2018-11-20 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rgt', '0004_rgtfailure_rgttestfailure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rgttestfailure',
            name='test_id',
            field=models.OneToOneField(db_column='test_id', on_delete=django.db.models.deletion.DO_NOTHING, to='rgt.RgtTest'),
        ),
    ]
